FROM ubuntu:18.04

ENV DISTRO_CODENAME bionic

RUN apt-get update
RUN apt update
RUN apt -y install curl gnupg2
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu ${DISTRO_CODENAME} main" > /etc/apt/sources.list.d/ros-melodic.list'

# RUN sh -c \"echo 'deb http://packages.ros.org/ros/ubuntu bionic main' | tee /etc/apt/sources.list.d/ros-melodic.list \"
# RUN sh -c \"echo 'deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main' | tee /etc/apt/sources.list.d/ros-melodic.list \"
# RUN sh -c echo 'deb http://packages.ros.org/ros/ubuntu bionic main' > /etc/apt/sources.list.d/ros-melodic.list

# RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
# RUN curl -sSL 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0xC1CF6E31E6BADE8868B172B4F42ED6FBAB17C654' | apt-key add -

RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
RUN apt-get update 

#ENV DEBIAN_FRONTEND=noninteractive
#ENV TZ=America/Sao_Paulo

RUN DEBIAN_FRONTEND=noninteractive TZ=America/Sao_Paulo apt-get -y install ros-melodic-desktop-full 
RUN DEBIAN_FRONTEND=noninteractive TZ=America/Sao_Paulo apt-get upgrade 

RUN apt-get -y install ros-melodic-depthimage-to-laserscan 
RUN apt-get -y install ros-melodic-slam-gmapping 
RUN apt-get -y install ros-melodic-rtabmap-ros 
RUN apt-get -y install ros-melodic-navigation 
RUN apt-get -y install ros-melodic-explore-lite 

##########################################################################